# Generated by Django 4.0.6 on 2022-08-01 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_moreuserdata_descripcion_moreuserdata_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moreuserdata',
            name='descripcion',
            field=models.CharField(max_length=200),
        ),
    ]
