# Generated by Django 4.0.6 on 2022-08-01 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_moreuserdata_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moreuserdata',
            name='descripcion',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
