# Generated by Django 4.0.6 on 2022-08-01 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_moreuserdata_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='moreuserdata',
            name='descripcion',
            field=models.CharField(max_length=140, null=True),
        ),
    ]
