# Generated by Django 4.0.6 on 2022-08-01 17:53

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('subtitulo', models.CharField(default='DEFAULT VALUE', max_length=200)),
                ('contenido', ckeditor.fields.RichTextField()),
                ('fecha_creacion', models.DateField(null=True)),
            ],
        ),
    ]
