# Generated by Django 4.0.6 on 2022-08-01 14:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CrearBlog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='descripcion',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
