# Generated by Django 4.0.6 on 2022-08-01 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrearBlog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='subtitulo',
            field=models.CharField(max_length=200),
        ),
    ]
