# Generated by Django 4.0.6 on 2022-08-01 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrearBlog', '0003_alter_blog_contenido'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='autor',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
